// <auto-generated />
using System;
using Librarian.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Librarian.DB.Migrations
{
    [DbContext(typeof(PostgresDatabaseContext))]
    partial class PostgresDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Librarian.Model.AttributeAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("AttributeAliases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "acoustid_id",
                            AttributeDefinitionId = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Alias = "album",
                            AttributeDefinitionId = 2,
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Alias = "album_artist",
                            AttributeDefinitionId = 3,
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Alias = "albumartistsort",
                            AttributeDefinitionId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            Alias = "replaygain_album_gain",
                            AttributeDefinitionId = 5,
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            Alias = "replaygain_album_peak",
                            AttributeDefinitionId = 6,
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            Alias = "artist",
                            AttributeDefinitionId = 7,
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            Alias = "artists",
                            AttributeDefinitionId = 7,
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            Alias = "artistsort",
                            AttributeDefinitionId = 8,
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Alias = "tbp",
                            AttributeDefinitionId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 11,
                            Alias = "composer",
                            AttributeDefinitionId = 12,
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            Alias = "tcm",
                            AttributeDefinitionId = 12,
                            Role = 0
                        },
                        new
                        {
                            Id = 13,
                            Alias = "ieng",
                            AttributeDefinitionId = 13,
                            Role = 0
                        },
                        new
                        {
                            Id = 14,
                            Alias = "tke",
                            AttributeDefinitionId = 14,
                            Role = 0
                        },
                        new
                        {
                            Id = 15,
                            Alias = "toal",
                            AttributeDefinitionId = 16,
                            Role = 0
                        },
                        new
                        {
                            Id = 16,
                            Alias = "replaygain_reference_loudness",
                            AttributeDefinitionId = 17,
                            Role = 0
                        },
                        new
                        {
                            Id = 17,
                            Alias = "tracktotal",
                            AttributeDefinitionId = 19,
                            Role = 0
                        },
                        new
                        {
                            Id = 18,
                            Alias = "track",
                            AttributeDefinitionId = 20,
                            Role = 0
                        },
                        new
                        {
                            Id = 19,
                            Alias = "musicmatch_trackartist",
                            AttributeDefinitionId = 21,
                            Role = 0
                        },
                        new
                        {
                            Id = 20,
                            Alias = "replaygain_track_gain",
                            AttributeDefinitionId = 22,
                            Role = 0
                        },
                        new
                        {
                            Id = 21,
                            Alias = "replaygain_track_peak",
                            AttributeDefinitionId = 23,
                            Role = 0
                        },
                        new
                        {
                            Id = 22,
                            Alias = "mimetype",
                            AttributeDefinitionId = 31,
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            Alias = "asin",
                            AttributeDefinitionId = 33,
                            Role = 0
                        },
                        new
                        {
                            Id = 24,
                            Alias = "barcode",
                            AttributeDefinitionId = 34,
                            Role = 0
                        },
                        new
                        {
                            Id = 25,
                            Alias = "upc",
                            AttributeDefinitionId = 34,
                            Role = 0
                        },
                        new
                        {
                            Id = 26,
                            Alias = "catalognumber",
                            AttributeDefinitionId = 35,
                            Role = 0
                        },
                        new
                        {
                            Id = 27,
                            Alias = "grouping",
                            AttributeDefinitionId = 37,
                            Role = 0
                        },
                        new
                        {
                            Id = 28,
                            Alias = "comment",
                            AttributeDefinitionId = 38,
                            Role = 0
                        },
                        new
                        {
                            Id = 29,
                            Alias = "compilation",
                            AttributeDefinitionId = 39,
                            Role = 0
                        },
                        new
                        {
                            Id = 30,
                            Alias = "law_rating",
                            AttributeDefinitionId = 40,
                            Role = 0
                        },
                        new
                        {
                            Id = 31,
                            Alias = "rating",
                            AttributeDefinitionId = 40,
                            Role = 0
                        },
                        new
                        {
                            Id = 32,
                            Alias = "content_type",
                            AttributeDefinitionId = 41,
                            Role = 0
                        },
                        new
                        {
                            Id = 33,
                            Alias = "copyright",
                            AttributeDefinitionId = 42,
                            Role = 0
                        },
                        new
                        {
                            Id = 34,
                            Alias = "credits",
                            AttributeDefinitionId = 43,
                            Role = 0
                        },
                        new
                        {
                            Id = 35,
                            Alias = "creation_time",
                            AttributeDefinitionId = 44,
                            Role = 0
                        },
                        new
                        {
                            Id = 36,
                            Alias = "date",
                            AttributeDefinitionId = 44,
                            Role = 0
                        },
                        new
                        {
                            Id = 37,
                            Alias = "originaldate",
                            AttributeDefinitionId = 44,
                            Role = 0
                        },
                        new
                        {
                            Id = 38,
                            Alias = "date_release",
                            AttributeDefinitionId = 45,
                            Role = 0
                        },
                        new
                        {
                            Id = 39,
                            Alias = "date_released",
                            AttributeDefinitionId = 45,
                            Role = 0
                        },
                        new
                        {
                            Id = 40,
                            Alias = "tdr",
                            AttributeDefinitionId = 45,
                            Role = 0
                        },
                        new
                        {
                            Id = 41,
                            Alias = "description",
                            AttributeDefinitionId = 46,
                            Role = 0
                        },
                        new
                        {
                            Id = 42,
                            Alias = "tds",
                            AttributeDefinitionId = 46,
                            Role = 0
                        },
                        new
                        {
                            Id = 43,
                            Alias = "director",
                            AttributeDefinitionId = 47,
                            Role = 0
                        },
                        new
                        {
                            Id = 44,
                            Alias = "encoded_by",
                            AttributeDefinitionId = 49,
                            Role = 0
                        },
                        new
                        {
                            Id = 45,
                            Alias = "encoded-by",
                            AttributeDefinitionId = 49,
                            Role = 0
                        },
                        new
                        {
                            Id = 46,
                            Alias = "encodedby",
                            AttributeDefinitionId = 49,
                            Role = 0
                        },
                        new
                        {
                            Id = 47,
                            Alias = "encoder",
                            AttributeDefinitionId = 50,
                            Role = 0
                        },
                        new
                        {
                            Id = 48,
                            Alias = "software",
                            AttributeDefinitionId = 50,
                            Role = 0
                        },
                        new
                        {
                            Id = 49,
                            Alias = "encodersettings",
                            AttributeDefinitionId = 51,
                            Role = 0
                        },
                        new
                        {
                            Id = 50,
                            Alias = "tss",
                            AttributeDefinitionId = 51,
                            Role = 0
                        },
                        new
                        {
                            Id = 51,
                            Alias = "language",
                            AttributeDefinitionId = 54,
                            Role = 0
                        },
                        new
                        {
                            Id = 52,
                            Alias = "location",
                            AttributeDefinitionId = 55,
                            Role = 0
                        },
                        new
                        {
                            Id = 53,
                            Alias = "location-eng",
                            AttributeDefinitionId = 55,
                            Role = 0
                        },
                        new
                        {
                            Id = 54,
                            Alias = "minor_version",
                            AttributeDefinitionId = 56,
                            Role = 0
                        },
                        new
                        {
                            Id = 55,
                            Alias = "organization",
                            AttributeDefinitionId = 57,
                            Role = 0
                        },
                        new
                        {
                            Id = 56,
                            Alias = "product",
                            AttributeDefinitionId = 58,
                            Role = 0
                        },
                        new
                        {
                            Id = 57,
                            Alias = "publisher",
                            AttributeDefinitionId = 59,
                            Role = 0
                        },
                        new
                        {
                            Id = 58,
                            Alias = "releasecountry",
                            AttributeDefinitionId = 60,
                            Role = 0
                        },
                        new
                        {
                            Id = 59,
                            Alias = "releasestatus",
                            AttributeDefinitionId = 62,
                            Role = 0
                        },
                        new
                        {
                            Id = 60,
                            Alias = "releasetype",
                            AttributeDefinitionId = 63,
                            Role = 0
                        },
                        new
                        {
                            Id = 61,
                            Alias = "script",
                            AttributeDefinitionId = 64,
                            Role = 0
                        },
                        new
                        {
                            Id = 62,
                            Alias = "tsiz",
                            AttributeDefinitionId = 65,
                            Role = 0
                        },
                        new
                        {
                            Id = 63,
                            Alias = "isrc",
                            AttributeDefinitionId = 66,
                            Role = 0
                        },
                        new
                        {
                            Id = 64,
                            Alias = "tid",
                            AttributeDefinitionId = 66,
                            Role = 0
                        },
                        new
                        {
                            Id = 65,
                            Alias = "woas",
                            AttributeDefinitionId = 67,
                            Role = 0
                        },
                        new
                        {
                            Id = 66,
                            Alias = "subtitle",
                            AttributeDefinitionId = 69,
                            Role = 0
                        },
                        new
                        {
                            Id = 67,
                            Alias = "tit3",
                            AttributeDefinitionId = 69,
                            Role = 0
                        },
                        new
                        {
                            Id = 68,
                            Alias = "tt3",
                            AttributeDefinitionId = 69,
                            Role = 0
                        },
                        new
                        {
                            Id = 69,
                            Alias = "summary",
                            AttributeDefinitionId = 70,
                            Role = 0
                        },
                        new
                        {
                            Id = 70,
                            Alias = "synopsis",
                            AttributeDefinitionId = 71,
                            Role = 0
                        },
                        new
                        {
                            Id = 71,
                            Alias = "title",
                            AttributeDefinitionId = 73,
                            Role = 0
                        },
                        new
                        {
                            Id = 72,
                            Alias = "ufid",
                            AttributeDefinitionId = 74,
                            Role = 0
                        },
                        new
                        {
                            Id = 73,
                            Alias = "uploader",
                            AttributeDefinitionId = 75,
                            Role = 0
                        },
                        new
                        {
                            Id = 74,
                            Alias = "written_by",
                            AttributeDefinitionId = 76,
                            Role = 0
                        },
                        new
                        {
                            Id = 75,
                            Alias = "tyer",
                            AttributeDefinitionId = 77,
                            Role = 0
                        },
                        new
                        {
                            Id = 76,
                            Alias = "year",
                            AttributeDefinitionId = 77,
                            Role = 0
                        },
                        new
                        {
                            Id = 77,
                            Alias = "originalyear",
                            AttributeDefinitionId = 78,
                            Role = 0
                        },
                        new
                        {
                            Id = 78,
                            Alias = "actor",
                            AttributeDefinitionId = 83,
                            Role = 0
                        },
                        new
                        {
                            Id = 79,
                            Alias = "bps",
                            AttributeDefinitionId = 84,
                            Role = 0
                        },
                        new
                        {
                            Id = 80,
                            Alias = "bps-eng",
                            AttributeDefinitionId = 84,
                            Role = 0
                        },
                        new
                        {
                            Id = 81,
                            Alias = "date_recorded",
                            AttributeDefinitionId = 86,
                            Role = 0
                        },
                        new
                        {
                            Id = 82,
                            Alias = "disc",
                            AttributeDefinitionId = 87,
                            Role = 0
                        },
                        new
                        {
                            Id = 83,
                            Alias = "duration",
                            AttributeDefinitionId = 88,
                            Role = 0
                        },
                        new
                        {
                            Id = 84,
                            Alias = "duration-eng",
                            AttributeDefinitionId = 88,
                            Role = 0
                        },
                        new
                        {
                            Id = 85,
                            Alias = "tlen",
                            AttributeDefinitionId = 88,
                            Role = 0
                        },
                        new
                        {
                            Id = 86,
                            Alias = "episodeid",
                            AttributeDefinitionId = 90,
                            Role = 0
                        },
                        new
                        {
                            Id = 87,
                            Alias = "episodenumber",
                            AttributeDefinitionId = 91,
                            Role = 0
                        },
                        new
                        {
                            Id = 88,
                            Alias = "episode_sort",
                            AttributeDefinitionId = 91,
                            Role = 0
                        },
                        new
                        {
                            Id = 89,
                            Alias = "genre",
                            AttributeDefinitionId = 92,
                            Role = 0
                        },
                        new
                        {
                            Id = 90,
                            Alias = "label",
                            AttributeDefinitionId = 93,
                            Role = 0
                        },
                        new
                        {
                            Id = 91,
                            Alias = "media",
                            AttributeDefinitionId = 94,
                            Role = 0
                        },
                        new
                        {
                            Id = 92,
                            Alias = "musicbrainz_albumartistid",
                            AttributeDefinitionId = 95,
                            Role = 0
                        },
                        new
                        {
                            Id = 93,
                            Alias = "musicbrainz_albumid",
                            AttributeDefinitionId = 96,
                            Role = 0
                        },
                        new
                        {
                            Id = 94,
                            Alias = "musicbrainz_artistid",
                            AttributeDefinitionId = 97,
                            Role = 0
                        },
                        new
                        {
                            Id = 95,
                            Alias = "musicbrainz_releasegroupid",
                            AttributeDefinitionId = 98,
                            Role = 0
                        },
                        new
                        {
                            Id = 96,
                            Alias = "musicbrainz_releasetrackid",
                            AttributeDefinitionId = 99,
                            Role = 0
                        },
                        new
                        {
                            Id = 97,
                            Alias = "musicbrainz_trackid",
                            AttributeDefinitionId = 100,
                            Role = 0
                        },
                        new
                        {
                            Id = 98,
                            Alias = "narratedby",
                            AttributeDefinitionId = 101,
                            Role = 0
                        },
                        new
                        {
                            Id = 99,
                            Alias = "producer",
                            AttributeDefinitionId = 102,
                            Role = 0
                        },
                        new
                        {
                            Id = 100,
                            Alias = "screenplay_by",
                            AttributeDefinitionId = 103,
                            Role = 0
                        },
                        new
                        {
                            Id = 101,
                            Alias = "season_number",
                            AttributeDefinitionId = 104,
                            Role = 0
                        },
                        new
                        {
                            Id = 102,
                            Alias = "seasonnumber",
                            AttributeDefinitionId = 104,
                            Role = 0
                        },
                        new
                        {
                            Id = 103,
                            Alias = "production_studio",
                            AttributeDefinitionId = 107,
                            Role = 0
                        },
                        new
                        {
                            Id = 104,
                            Alias = "disctotal",
                            AttributeDefinitionId = 108,
                            Role = 0
                        },
                        new
                        {
                            Id = 105,
                            Alias = "filename",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Librarian.Model.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Group")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Group", "Name")
                        .IsUnique();

                    b.ToTable("AttributeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "AcoustID identifier",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "AcoustID ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Album",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Album artist",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Album artist (sort)",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "The ideal listening gain for an entire album",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Album gain",
                            Type = 4,
                            Unit = ""
                        },
                        new
                        {
                            Id = 6,
                            Description = "Peak album amplitude, used to predict whether the required replay gain adjustment will cause clipping during playback",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Album peak",
                            Type = 4,
                            Unit = "dB"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Artist",
                            Type = 0,
                            Unit = "dB"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Artist (sort)",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Beats per minute",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Bits per sample",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Channels",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Composer",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Engineer",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Initial key",
                            Type = 0,
                            Unit = "bpm"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Lyrics",
                            Type = 1,
                            Unit = "bps"
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Original album",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Reference loudness",
                            Type = 4,
                            Unit = ""
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Sample rate",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Total tracks",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 20,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Track ",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 21,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Track artist",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 22,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Track gain",
                            Type = 4,
                            Unit = ""
                        },
                        new
                        {
                            Id = 23,
                            Description = "",
                            Group = "Audio",
                            IsReadOnly = false,
                            Name = "Track peak",
                            Type = 4,
                            Unit = ""
                        },
                        new
                        {
                            Id = 24,
                            Description = "Date and time when the file was created on disk.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "Date created",
                            Type = 5,
                            Unit = ""
                        },
                        new
                        {
                            Id = 25,
                            Description = "Date and time when the file was last modified.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "Date modified",
                            Type = 5,
                            Unit = ""
                        },
                        new
                        {
                            Id = 26,
                            Description = "The file extension.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "File extension",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 27,
                            Description = "The file name as it appears on disk.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "File name",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 28,
                            Description = "File type as detected by the 'file' command.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "File type",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 29,
                            Description = "The full file system path to the file.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "Full path",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 30,
                            Description = "Number of items (files or folders) in the directory.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "Item count",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 31,
                            Description = "The detected mime type of the file.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "Mime type",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 32,
                            Description = "The size of the file in bytes.",
                            Group = "File attributes",
                            IsReadOnly = false,
                            Name = "Size",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 33,
                            Description = "Product identifier used by the Amazon store",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Amazon Standard Identification Number (ASIN)",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 34,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Bar code",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 35,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Catalog number",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 36,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Category",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 37,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Collection",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 38,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Comment",
                            Type = 1,
                            Unit = ""
                        },
                        new
                        {
                            Id = 39,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Compilation",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 40,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Content rating",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 41,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Content type",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 42,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Copyright",
                            Type = 1,
                            Unit = ""
                        },
                        new
                        {
                            Id = 43,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Credits",
                            Type = 1,
                            Unit = ""
                        },
                        new
                        {
                            Id = 44,
                            Description = "Date when this file was created.",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Date created",
                            Type = 5,
                            Unit = ""
                        },
                        new
                        {
                            Id = 45,
                            Description = "Date when this file was released.",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Date released",
                            Type = 5,
                            Unit = ""
                        },
                        new
                        {
                            Id = 46,
                            Description = "Long description of the file, can be formatted with MarkDown.",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Description",
                            Type = 2,
                            Unit = ""
                        },
                        new
                        {
                            Id = 47,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Director",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 48,
                            Description = "Name that will be displayed in the metadata file browser.",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Display name",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 49,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Encoded by",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 50,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Encoder",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 51,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Encoder settings",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 52,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Id",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 53,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Index",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 54,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Language",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 55,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Location",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 56,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Minor version",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 57,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Organization",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 58,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Product",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 59,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Publisher",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 60,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Release country",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 61,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Release notes",
                            Type = 2,
                            Unit = ""
                        },
                        new
                        {
                            Id = 62,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Release status",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 63,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Release type",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 64,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Script",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 65,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Size",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 66,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Source",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 67,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Source URL",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 68,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Subcategory",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 69,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Subtitle",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 70,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Summary",
                            Type = 1,
                            Unit = ""
                        },
                        new
                        {
                            Id = 71,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Synopsis",
                            Type = 1,
                            Unit = ""
                        },
                        new
                        {
                            Id = 72,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Tag",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 73,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Title",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 74,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Unique file identifier (UFID)",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 75,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Uploader",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 76,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Written by",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 77,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Year",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 78,
                            Description = "",
                            Group = "General",
                            IsReadOnly = false,
                            Name = "Year created",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 79,
                            Description = "Ratio obtained by dividing the width by the height.",
                            Group = "Image",
                            IsReadOnly = false,
                            Name = "Aspect ratio",
                            Type = 4,
                            Unit = ""
                        },
                        new
                        {
                            Id = 80,
                            Description = "Image height in pixels.",
                            Group = "Image",
                            IsReadOnly = false,
                            Name = "Height",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 81,
                            Description = "Total number of pixels in this image.",
                            Group = "Image",
                            IsReadOnly = false,
                            Name = "Pixels",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 82,
                            Description = "Image width in pixels.",
                            Group = "Image",
                            IsReadOnly = false,
                            Name = "Width",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 83,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Actor",
                            Type = 0,
                            Unit = "dB"
                        },
                        new
                        {
                            Id = 84,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Bit rate",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 85,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Codec",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 86,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Date recorded",
                            Type = 5,
                            Unit = ""
                        },
                        new
                        {
                            Id = 87,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Disc",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 88,
                            Description = "Media duration.",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Duration",
                            Type = 6,
                            Unit = ""
                        },
                        new
                        {
                            Id = 89,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "End time",
                            Type = 6,
                            Unit = ""
                        },
                        new
                        {
                            Id = 90,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Episode ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 91,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Episode number",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 92,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Genre",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 93,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Label",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 94,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Media format",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 95,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "MusicBrainz album artist ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 96,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "MusicBrainz album ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 97,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "MusicBrainz artist ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 98,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "MusicBrainz release group ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 99,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "MusicBrainz release track ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 100,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "MusicBrainz track ID",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 101,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Narrated by",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 102,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Producer",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 103,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Screenplay by",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 104,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Season number",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 105,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Start time",
                            Type = 6,
                            Unit = ""
                        },
                        new
                        {
                            Id = 106,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Stream type",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 107,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Studio",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 108,
                            Description = "",
                            Group = "Media",
                            IsReadOnly = false,
                            Name = "Total discs",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 109,
                            Description = "Version of this package.",
                            Group = "Package",
                            IsReadOnly = false,
                            Name = "Version",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 110,
                            Description = "System architecture for which this software was compiled",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Architecture",
                            Type = 0,
                            Unit = "dB"
                        },
                        new
                        {
                            Id = 111,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "End of life date",
                            Type = 5,
                            Unit = "dB"
                        },
                        new
                        {
                            Id = 112,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Installation instructions",
                            Type = 2,
                            Unit = ""
                        },
                        new
                        {
                            Id = 113,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Minimum CPU",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 114,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Minimum disk space",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 115,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Minimum RAM",
                            Type = 3,
                            Unit = ""
                        },
                        new
                        {
                            Id = 116,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Platform",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 117,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "Serial key",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 118,
                            Description = "",
                            Group = "Software",
                            IsReadOnly = false,
                            Name = "User interface",
                            Type = 0,
                            Unit = ""
                        },
                        new
                        {
                            Id = 119,
                            Description = "",
                            Group = "Video",
                            IsReadOnly = false,
                            Name = "Frame rate",
                            Type = 4,
                            Unit = ""
                        },
                        new
                        {
                            Id = 120,
                            Description = "",
                            Group = "Video",
                            IsReadOnly = false,
                            Name = "Frames",
                            Type = 3,
                            Unit = ""
                        });
                });

            modelBuilder.Entity("Librarian.Model.BlobAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FileId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ProviderAttributeId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubResourceId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("FileId");

                    b.HasIndex("SubResourceId");

                    b.ToTable("BlobAttributes");
                });

            modelBuilder.Entity("Librarian.Model.DateAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FileId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ProviderAttributeId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubResourceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Value")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("FileId");

                    b.HasIndex("SubResourceId");

                    b.ToTable("DateAttributes");
                });

            modelBuilder.Entity("Librarian.Model.FloatAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FileId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ProviderAttributeId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubResourceId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("FileId");

                    b.HasIndex("SubResourceId");

                    b.ToTable("FloatAttributes");
                });

            modelBuilder.Entity("Librarian.Model.IndexedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Exists")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IndexLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedsUpdating")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("IndexedFiles");
                });

            modelBuilder.Entity("Librarian.Model.IndexedFileContents", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("ContentSearch")
                        .HasColumnType("tsvector");

                    b.HasKey("FileId");

                    b.ToTable("IndexedFileContents");
                });

            modelBuilder.Entity("Librarian.Model.IntegerAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FileId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ProviderAttributeId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubResourceId")
                        .HasColumnType("integer");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("FileId");

                    b.HasIndex("SubResourceId");

                    b.ToTable("IntegerAttributes");
                });

            modelBuilder.Entity("Librarian.Model.SubResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<long?>("InternalId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("SubResources");
                });

            modelBuilder.Entity("Librarian.Model.TextAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FileId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ProviderAttributeId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("ValueSearch")
                        .HasColumnType("tsvector");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("FileId");

                    b.HasIndex("SubResourceId");

                    b.ToTable("TextAttributes");
                });

            modelBuilder.Entity("Librarian.Model.AttributeAlias", b =>
                {
                    b.HasOne("Librarian.Model.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId");

                    b.Navigation("AttributeDefinition");
                });

            modelBuilder.Entity("Librarian.Model.BlobAttribute", b =>
                {
                    b.HasOne("Librarian.Model.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithMany("BlobMetadata")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.SubResource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceId");

                    b.Navigation("AttributeDefinition");

                    b.Navigation("File");

                    b.Navigation("SubResource");
                });

            modelBuilder.Entity("Librarian.Model.DateAttribute", b =>
                {
                    b.HasOne("Librarian.Model.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithMany("DateMetadata")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.SubResource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceId");

                    b.Navigation("AttributeDefinition");

                    b.Navigation("File");

                    b.Navigation("SubResource");
                });

            modelBuilder.Entity("Librarian.Model.FloatAttribute", b =>
                {
                    b.HasOne("Librarian.Model.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithMany("FloatMetadata")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.SubResource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceId");

                    b.Navigation("AttributeDefinition");

                    b.Navigation("File");

                    b.Navigation("SubResource");
                });

            modelBuilder.Entity("Librarian.Model.IndexedFileContents", b =>
                {
                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithOne("Contents")
                        .HasForeignKey("Librarian.Model.IndexedFileContents", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Librarian.Model.IntegerAttribute", b =>
                {
                    b.HasOne("Librarian.Model.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithMany("IntegerMetadata")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.SubResource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceId");

                    b.Navigation("AttributeDefinition");

                    b.Navigation("File");

                    b.Navigation("SubResource");
                });

            modelBuilder.Entity("Librarian.Model.SubResource", b =>
                {
                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Librarian.Model.TextAttribute", b =>
                {
                    b.HasOne("Librarian.Model.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.IndexedFile", "File")
                        .WithMany("TextMetadata")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Model.SubResource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceId");

                    b.Navigation("AttributeDefinition");

                    b.Navigation("File");

                    b.Navigation("SubResource");
                });

            modelBuilder.Entity("Librarian.Model.IndexedFile", b =>
                {
                    b.Navigation("BlobMetadata");

                    b.Navigation("Contents");

                    b.Navigation("DateMetadata");

                    b.Navigation("FloatMetadata");

                    b.Navigation("IntegerMetadata");

                    b.Navigation("TextMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
