/* THIS FILE IS AUTOGENERATED DO NOT EDIT
 * The file is generated from MetadataAttributes.csv.
 */
namespace Librarian.Model.MetadataAttributes
{
    public static class Audio
    {
        public static readonly int AcoustIDID = 1;
        public static readonly int Album = 2;
        public static readonly int AlbumArtist = 3;
        public static readonly int AlbumArtistSort = 4;
        public static readonly int AlbumGain = 5;
        public static readonly int AlbumPeak = 6;
        public static readonly int Artist = 7;
        public static readonly int ArtistSort = 8;
        public static readonly int BeatsPerMinute = 9;
        public static readonly int BitsPerSample = 10;
        public static readonly int Channels = 11;
        public static readonly int Composer = 12;
        public static readonly int Engineer = 13;
        public static readonly int InitialKey = 14;
        public static readonly int Lyrics = 15;
        public static readonly int OriginalAlbum = 16;
        public static readonly int ReferenceLoudness = 17;
        public static readonly int SampleRate = 18;
        public static readonly int TotalTracks = 19;
        public static readonly int Track = 20;
        public static readonly int TrackArtist = 21;
        public static readonly int TrackGain = 22;
        public static readonly int TrackPeak = 23;
    }

    public static class FileAttributes
    {
        public static readonly int DateCreated = 24;
        public static readonly int DateModified = 25;
        public static readonly int FileExtension = 26;
        public static readonly int FileName = 27;
        public static readonly int FileType = 28;
        public static readonly int FullPath = 29;
        public static readonly int ItemCount = 30;
        public static readonly int MimeType = 31;
        public static readonly int Size = 32;
    }

    public static class General
    {
        public static readonly int AmazonStandardIdentificationNumberASIN = 33;
        public static readonly int BarCode = 34;
        public static readonly int CatalogNumber = 35;
        public static readonly int Category = 36;
        public static readonly int Collection = 37;
        public static readonly int Comment = 38;
        public static readonly int Compilation = 39;
        public static readonly int ContentRating = 40;
        public static readonly int ContentType = 41;
        public static readonly int Copyright = 42;
        public static readonly int Credits = 43;
        public static readonly int DateCreated = 44;
        public static readonly int DateReleased = 45;
        public static readonly int Description = 46;
        public static readonly int Director = 47;
        public static readonly int DisplayName = 48;
        public static readonly int EncodedBy = 49;
        public static readonly int Encoder = 50;
        public static readonly int EncoderSettings = 51;
        public static readonly int Id = 52;
        public static readonly int Index = 53;
        public static readonly int Language = 54;
        public static readonly int Location = 55;
        public static readonly int MinorVersion = 56;
        public static readonly int Organization = 57;
        public static readonly int Product = 58;
        public static readonly int Publisher = 59;
        public static readonly int ReleaseCountry = 60;
        public static readonly int ReleaseNotes = 61;
        public static readonly int ReleaseStatus = 62;
        public static readonly int ReleaseType = 63;
        public static readonly int Script = 64;
        public static readonly int Size = 65;
        public static readonly int Source = 66;
        public static readonly int SourceURL = 67;
        public static readonly int Subcategory = 68;
        public static readonly int Subtitle = 69;
        public static readonly int Summary = 70;
        public static readonly int Synopsis = 71;
        public static readonly int Tag = 72;
        public static readonly int Title = 73;
        public static readonly int UniqueFileIdentifierUFID = 74;
        public static readonly int Uploader = 75;
        public static readonly int WrittenBy = 76;
        public static readonly int Year = 77;
        public static readonly int YearCreated = 78;
    }

    public static class Image
    {
        public static readonly int AspectRatio = 79;
        public static readonly int Height = 80;
        public static readonly int Pixels = 81;
        public static readonly int Width = 82;
    }

    public static class Media
    {
        public static readonly int Actor = 83;
        public static readonly int BitRate = 84;
        public static readonly int Codec = 85;
        public static readonly int DateRecorded = 86;
        public static readonly int Disc = 87;
        public static readonly int Duration = 88;
        public static readonly int EndTime = 89;
        public static readonly int EpisodeID = 90;
        public static readonly int EpisodeNumber = 91;
        public static readonly int Genre = 92;
        public static readonly int Label = 93;
        public static readonly int MediaFormat = 94;
        public static readonly int MusicBrainzAlbumArtistID = 95;
        public static readonly int MusicBrainzAlbumID = 96;
        public static readonly int MusicBrainzArtistID = 97;
        public static readonly int MusicBrainzReleaseGroupID = 98;
        public static readonly int MusicBrainzReleaseTrackID = 99;
        public static readonly int MusicBrainzTrackID = 100;
        public static readonly int NarratedBy = 101;
        public static readonly int Producer = 102;
        public static readonly int ScreenplayBy = 103;
        public static readonly int SeasonNumber = 104;
        public static readonly int StartTime = 105;
        public static readonly int StreamType = 106;
        public static readonly int Studio = 107;
        public static readonly int TotalDiscs = 108;
    }

    public static class Package
    {
        public static readonly int Version = 109;
    }

    public static class Software
    {
        public static readonly int Architecture = 110;
        public static readonly int EndOfLifeDate = 111;
        public static readonly int InstallationInstructions = 112;
        public static readonly int MinimumCPU = 113;
        public static readonly int MinimumDiskSpace = 114;
        public static readonly int MinimumRAM = 115;
        public static readonly int Platform = 116;
        public static readonly int SerialKey = 117;
        public static readonly int UserInterface = 118;
    }

    public static class Video
    {
        public static readonly int FrameRate = 119;
        public static readonly int Frames = 120;
    }

}
