/* THIS FILE IS AUTOGENERATED DO NOT EDIT
 * The file is generated from MetadataFields.csv.
 */
namespace Librarian.Model.MetadataFields
{
    public static class FileAttributes
    {
        public static readonly MetadataAttribute DateCreated = new (name: "Date created", group: "File attributes", type: MetadataType.Date);
        public static readonly MetadataAttribute DateModified = new (name: "Date modified", group: "File attributes", type: MetadataType.Date);
        public static readonly MetadataAttribute FileExtension = new (name: "File extension", group: "File attributes", type: MetadataType.Text);
        public static readonly MetadataAttribute FileName = new (name: "File name", group: "File attributes", type: MetadataType.Text);
        public static readonly MetadataAttribute FullPath = new (name: "Full path", group: "File attributes", type: MetadataType.Text);
        public static readonly MetadataAttribute MimeType = new (name: "Mime type", group: "File attributes", type: MetadataType.Text);
        public static readonly MetadataAttribute Size = new (name: "Size", group: "File attributes", type: MetadataType.Integer);
    }

    public static class General
    {
        public static readonly MetadataAttribute Category = new (name: "Category", group: "General", type: MetadataType.Text);
        public static readonly MetadataAttribute DateReleased = new (name: "Date released", group: "General", type: MetadataType.Date);
        public static readonly MetadataAttribute Description = new (name: "Description", group: "General", type: MetadataType.FormattedText);
        public static readonly MetadataAttribute DisplayName = new (name: "Display name", group: "General", type: MetadataType.Text);
        public static readonly MetadataAttribute Language = new (name: "Language", group: "General", type: MetadataType.Text);
        public static readonly MetadataAttribute ReleaseNotes = new (name: "Release notes", group: "General", type: MetadataType.FormattedText);
        public static readonly MetadataAttribute Subcategory = new (name: "Subcategory", group: "General", type: MetadataType.Text);
        public static readonly MetadataAttribute Tag = new (name: "Tag", group: "General", type: MetadataType.Text);
    }

    public static class Image
    {
        public static readonly MetadataAttribute Height = new (name: "Height", group: "Image", type: MetadataType.Integer);
        public static readonly MetadataAttribute Width = new (name: "Width", group: "Image", type: MetadataType.Integer);
    }

    public static class Media
    {
        public static readonly MetadataAttribute Duration = new (name: "Duration", group: "Media", type: MetadataType.TimeSpan);
    }

    public static class Package
    {
        public static readonly MetadataAttribute Version = new (name: "Version", group: "Package", type: MetadataType.Text);
    }

    public static class Software
    {
        public static readonly MetadataAttribute Architecture = new (name: "Architecture", group: "Software", type: MetadataType.Text);
        public static readonly MetadataAttribute EndOfLifeDate = new (name: "End of life date", group: "Software", type: MetadataType.Date);
        public static readonly MetadataAttribute InstallationInstructions = new (name: "Installation instructions", group: "Software", type: MetadataType.FormattedText);
        public static readonly MetadataAttribute MinimumCPU = new (name: "Minimum CPU", group: "Software", type: MetadataType.Text);
        public static readonly MetadataAttribute MinimumDiskSpace = new (name: "Minimum disk space", group: "Software", type: MetadataType.Integer);
        public static readonly MetadataAttribute MinimumRAM = new (name: "Minimum RAM", group: "Software", type: MetadataType.Integer);
        public static readonly MetadataAttribute Platform = new (name: "Platform", group: "Software", type: MetadataType.Text);
        public static readonly MetadataAttribute SerialKey = new (name: "Serial key", group: "Software", type: MetadataType.Text);
        public static readonly MetadataAttribute UserInterface = new (name: "User interface", group: "Software", type: MetadataType.Text);
    }

    public static class Helper
    {
        public static readonly MetadataAttribute[] AllFields = new[]
        {
            FileAttributes.FileName,
            FileAttributes.FullPath,
            FileAttributes.DateCreated,
            FileAttributes.DateModified,
            FileAttributes.Size,
            FileAttributes.MimeType,
            FileAttributes.FileExtension,
            General.DisplayName,
            General.Description,
            Image.Width,
            Image.Height,
            Media.Duration,
            Package.Version,
            General.DateReleased,
            Software.EndOfLifeDate,
            Software.Architecture,
            Software.MinimumCPU,
            Software.MinimumRAM,
            Software.MinimumDiskSpace,
            Software.UserInterface,
            Software.Platform,
            Software.SerialKey,
            General.Tag,
            General.ReleaseNotes,
            Software.InstallationInstructions,
            General.Language,
            General.Category,
            General.Subcategory,
        };
    }
}
